# Generated by Django 3.1.7 on 2021-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0002_auto_20210418_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
