# Generated by Django 3.1.7 on 2021-04-27 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0003_university_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='unireview',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
