# Generated by Django 3.1.7 on 2021-05-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0004_unireview_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unireview',
            name='score',
            field=models.IntegerField(verbose_name='All Ratings'),
        ),
    ]
