# Generated by Django 3.1.7 on 2021-05-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0005_auto_20210503_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniReview',
        ),
    ]
