# Generated by Django 3.1.7 on 2021-05-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LecturerReview',
        ),
    ]
